# Generated by Django 5.2.1 on 2025-06-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
